---
config:
  layout: elk
---
flowchart TD
  Книга -->|экземпляр| Литературное_произведение
  Литературное_произведение -->|имеет_свойство| Жанр
  Литературное_произведение -->|имеет_свойство| Форма
  Письменная_работа -->|подмножество| Литературное_произведение
  Автор -->|создаёт| Книга
  Автор -->|создаёт| Литературное_произведение
  Издательство -->|издаёт| Книга
  Издательство -->|издаёт| Литературное_произведение
  Жанр -->|отличается_от| Форма
  Детектив -->|поджанр| Художественная_литература
  Драма -->|поджанр| Художественная_литература
  Фэнтези -->|поджанр| Художественная_литература
  Триллер -->|поджанр| Художественная_литература
  Художественная_литература -->|вид| Жанр
  Специальная_литература -->|вид| Жанр
  Форма -->|отличается_от| Жанр
  Роман -->|вид| Форма
  Роман -->|подвид| Проза
  Повесть -->|вид| Форма
  Повесть -->|подвид| Проза
  Антология -->|вид| Форма
  Антология -->|содержит| Литературное_произведение
  Антология -->|содержит| Письменная_работа
  Проза -->|вид| Форма
  Стихотворение -->|вид| Форма
  Энциклопедия -->|вид| Форма
  Энциклопедия -->|подвид| Специальная_литература
  Словарь -->|вид| Форма
  Словарь -->|подвид| Специальная_литература