@startuml

class "Хобби" {
}

class "Творческие хобби"
class "Активные хобби"
class "Интеллектуальные хобби"
class "Домашние хобби"

"Хобби" --|> "Творческие хобби"
"Хобби" --|> "Активные хобби"
"Хобби" --|> "Интеллектуальные хобби"
"Хобби" --|> "Домашние хобби"

class "Рисование"
class "Чтение"
class "Музыка"
class "Настольные игры"
class "Конструирование"
class "Спорт"
class "Садоводство"
class "Научные эксперименты"
class "Кулинария"
class "Танцы"
class "Вышивание"
class "Актерское мастерство"
class "Видеоигры"

"Творческие хобби" --|> "Рисование"
"Творческие хобби" --|> "Музыка"
"Творческие хобби" --|> "Актерское мастерство"
"Творческие хобби" --|> "Конструирование"
"Творческие хобби" --|> "Вышивание"

"Интеллектуальные хобби" --|> "Чтение"
"Интеллектуальные хобби" --|> "Настольные игры"
"Интеллектуальные хобби" --|> "Научные эксперименты"
"Интеллектуальные хобби" --|> "Конструирование"
"Интеллектуальные хобби" --|> "Видеоигры" 

"Активные хобби" --|> "Спорт"
"Активные хобби" --|> "Танцы"
"Активные хобби" --|> "Садоводство"

"Домашние хобби" --|> "Настольные игры"
"Домашние хобби" --|> "Кулинария"
"Домашние хобби" --|> "Видеоигры" 


@enduml
